openapi: 3.0.1
info:
  title: testApi123new
  description: ''
  version: v2
servers:
  - url: https://testapim-cm-east1.azure-api.net/testApi123/v2
paths:
  /testpost1:
    post:
      summary: testpost1
      description: testpost1
      operationId: testpost1
      responses:
        '200':
          description: ''
  /testget1:
    get:
      summary: testGet1
      description: testGet1
      operationId: testget1
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]