openapi: 3.0.1
info:
  title: sampleapi100
  description: ''
  version: '1.0'
servers:
  - url: https://apimarektest2.azure-api.net/sampleapi100
paths:
  /post100:
    post:
      summary: post100
      description: post100
      operationId: post100
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]