openapi: 3.0.1
info:
  title: sampleapi101
  description: hello api sample 101
  version: '1.0'
servers:
  - url: https://apimarektest2.azure-api.net/sampleapi101
paths:
  /get101:
    get:
      summary: get101
      description: get101
      operationId: get101
      responses:
        '200':
          description: ''
  /post101:
    post:
      summary: post101
      description: post101
      operationId: post101
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]