apimServiceName: apimArekTest2
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "https://www.search2.com"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#TESTSECRETVALUE#}"
  - name: helloworldfromfuncapp-key
    properties:
      displayName: helloworldfromfuncapp-key
      value: "{#helloworldfromfuncappkey#}"
