apimServiceName: apimArekTest2
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "www.TEST.com"
  - name: testkvsec
    properties:
      displayName: testkvsec
      keyVault:
        secretIdentifier: "https://kv-apimlz-dr-10max.vault.azure.net/secrets/testSecret1"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#TESTSECRETVALUE#}"
backends:
  - name: testBackend1
    properties:
      url: "https://helloworldfromprodfuncapp.azurewebsites.netChanged"  
