apimServiceName: apimArekTest2
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "{#vars.TESTNONSECRETVALUE#}"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#TESTSECRETVALUE#}"
backends:
  - name: testBackend1
    properties:
      url: "https://helloworldfromprodfuncapp.azurewebsites.netChanged"  
