openapi: 3.0.1
info:
  title: b2cIntegration
  description: ''
  version: '1.0'
servers:
  - url: https://apimarektest2.azure-api.net/b2cintegration
paths:
  /test1:
    post:
      summary: test1
      description: test1
      operationId: test1
      responses:
        '200':
          description: ''
    get:
      summary: test1
      description: test1
      operationId: 664d58757353f977a56e88ef
      responses:
        '200':
          description: ''
  /testmock:
    post:
      summary: testmock
      description: test1
      operationId: 664e4cba938270c47d0b5365
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]