name: B2C Extract

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        type: string
        default: 'dev'

  workflow_dispatch:
    inputs:
      environment:
        description: 'environment to extract from'
        required: true
        type: environment

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  apiops_release_version: v4.1.2
  RUNNER_DEBUG: 1

jobs:
  APIM-Import-APIs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.B2C_AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.B2C_AZURE_CLIENT_SECRET }}
      B2C_TENANT: ${{ secrets.B2C_TENANT }}

    steps:

      - uses: actions/checkout@v3

      - name: Install IefPolicies PowerShell Module
        run: |
          Install-Module -Name IefPolicies -RequiredVersion 2.2.6 -Force -Scope CurrentUser
        shell: pwsh

      - name: Connect to Azure AD B2C and Export IEF Policies
        run: |
          Connect-IefPolicies -tenant "${{ env.B2C_TENANT }}" -clientId "${{ env.AZURE_CLIENT_ID }}" -clientSecret "${{ env.AZURE_CLIENT_SECRET }}"
          mkdir -p ${{ GITHUB.WORKSPACE }}/ief-policies
          cd ief-policies
          Export-IEFPolicies
        shell: pwsh

      # - name: Export IEF Policies
      #   run: |
      #     Export-IEFPolicies
      #     mkdir -p ${{ GITHUB.WORKSPACE }}/ief-policies
      #     cp -r ./*.xml ${{ GITHUB.WORKSPACE }}/ief-policies/
      #   shell: pwsh

      - name: Commit and Push IEF Policies to New Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b export-ief-policies
          git add ief-policies/
          git commit -m "Exported IEF Policies"
          git push -u origin export-ief-policies
        shell: pwsh
